name: gradient_text
description: "A new Flutter package project."
version: 1.0.3
homepage: https://github.com/SpaceBuckett/gradient_text

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

